version: '3'

services:
#  postgresというデータベース
  db:
    image: postgres
    hostname: postgres
    container_name: db_postgres

#  Django
  web:
    hostname: django
    container_name: django
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db